Repository boostcampwm2023/web18_Dandi, pull requests merged in 2023-12, with the labels that each got.

#210 [FE] 친구관리 Modal에서 해당하지 않는 사용자가 출력되는 문제 수정
  frontend/src/components/Home/FriendRequest.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
Labels: FE 🎨, Bug 🐞

#193 [BE] 엘라스틱 서치 검색 기능 구현
  .format.env
  backend/package.json
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.module.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#205 [BE] 특정 태그가 포함된 일기 조회 API 구현
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
Labels: BE 💻, Feature 🎉

#200 [BE] 리액션 수정 API 구현
  backend/src/reactions/dto/reaction.dto.ts
  backend/src/reactions/reactions.controller.ts
  backend/src/reactions/reactions.repository.ts
  backend/src/reactions/reactions.service.ts
Labels: BE 💻, Feature 🎉

#202 [BE] 프로필 수정 API 작성
  backend/src/images/images.controller.ts
  backend/src/images/images.module.ts
  backend/src/users/dto/user.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: BE 💻, Feature 🎉

#207 [BE] 특정 사용자의 일기 조회 API 요청 파라미터 수정
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
Labels: BE 💻, Feature 🎉

#213 [BE] 토큰 관리 로직 수정 & 로그아웃 API 구현
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.repository.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/guards/jwtAuth.guard.ts
  backend/src/auth/utils/auth.constant.ts
  yarn.lock
Labels: BE 💻, Refactor 🛠️, Feature 🎉

#204 [BE] 친구 삭제 API 작성
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
Labels: BE 💻, Feature 🎉

#212 [FE] 홈 페이지 - 친구관리, 내 정보 수정
  frontend/src/api/FriendModal.ts
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
  frontend/src/util/apiPath.ts
Labels: FE 🎨, Feature 🎉

#218 [BE] 검색 API 페이징 처리 | Full Text Index 적용
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/entity/diary.entity.ts
Labels: enhancement, BE 💻

#223 [BE/FE] CORS Origin 변경
  backend/src/main.ts
  frontend/src/util/apiPath.ts
Labels: BE 💻, FE 🎨, Bug 🐞

#225 [FE] 내가 작성한 일기 API 연동 마무리 & 로직 수정, 감정 통계 API 연동
  frontend/src/api/DiaryList.ts
  frontend/src/api/EmotionStat.ts
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Common/ProfileItem.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/UserSearchContent.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/types/components/Common/DiaryList.ts
  frontend/src/types/components/Home/Profile.ts
  frontend/src/util/apiPath.ts
  frontend/src/util/constants.ts
  frontend/src/util/funcs.ts
Labels: FE 🎨, Bug 🐞, Feature 🎉

#237 [FE] MyDiary 에러 해결
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/pages/MyDiary.tsx
Labels: FE 🎨, Bug 🐞

#242 [FE] 버그 수정 및 기능 추가
  frontend/src/api/DiaryList.ts
  frontend/src/api/Feed.ts
  frontend/src/api/KeywordSearch.ts
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/types/components/MyDiary/MonthContainer.ts
  frontend/src/types/pages/MyDiary.ts
  frontend/src/util/apiPath.ts
Labels: FE 🎨, Bug 🐞

#232 [BE] 친구 삭제 오류 수정 | DB 유니크 값 설정
  backend/src/friends/friends.service.ts
  backend/src/users/entity/user.entity.ts
  backend/src/users/users.controller.ts
Labels: BE 💻, Bug 🐞

#243 [FE] UI 동작 개선
  frontend/src/api/FriendModal.ts
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/util/AuthRoutes.tsx
  frontend/src/util/PrivateRoutes.tsx
Labels: enhancement, FE 🎨, Feature 🎉

#248 [FE] 일기 삭제 후 삭제된 데이터 불러오던 문제 해결
  frontend/src/pages/Detail.tsx
  frontend/src/pages/MyDiary.tsx
Labels: FE 🎨, Bug 🐞

#249 [FE] 친구 관리 요청을 보낸 후에 리렌더링이 되지 않는 문제 수정
  frontend/src/api/FriendModal.ts
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/ProfileEdit.tsx
Labels: enhancement, FE 🎨

#245 [FE] 검색 API 연동 완료, 피드 API 연동 중
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/util/constants.ts
Labels: FE 🎨, Feature 🎉

#252 [FE] 친구 홈의 프로필에서 출력하는 데이터 변경
  frontend/src/components/Home/Profile.tsx
Labels: FE 🎨, Feature 🎉

#255 [BE] 사용자 정보 조회 응답 수정 | lazy loading 삭제
  backend/src/users/dto/user.dto.ts
  backend/src/users/entity/user.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.repository.ts
  backend/src/users/users.service.ts
Labels: enhancement, BE 💻

#244 [BE] 일기 lazy loading 삭제, Repository 반환값 설정
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/entity/diary.entity.ts
Labels: enhancement, BE 💻

#256 [BE] 친구신청 상태와 관계없이 친구를 카운트하는 문제 수정
  backend/src/users/users.service.ts
Labels: BE 💻, Bug 🐞

#253 [FE] 감정 통계 API 재설정 & 통계 기간 input min, max 설정
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/globals.css
  frontend/src/util/constants.ts
  frontend/src/util/funcs.ts
Labels: FE 🎨, Feature 🎉

#258 [BE] 이미지 리사이징
  backend/package.json
  backend/src/images/images.repository.ts
  backend/src/images/images.service.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#260 [BE] friends, reactions module 쿼리 개선
  backend/src/diaries/diaries.repository.ts
  backend/src/friends/friends.repository.ts
  backend/src/reactions/reactions.controller.ts
  backend/src/reactions/reactions.repository.ts
  backend/src/reactions/reactions.service.ts
Labels: enhancement, BE 💻, Refactor 🛠️

#268 [BE] access token 갱신 에러 해결
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
Labels: BE 💻, Bug 🐞

#269 [FE] 오류 해결
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/MyDiary.tsx
Labels: FE 🎨, Bug 🐞

#271 [공통] 오류 해결
  backend/src/diaries/diaries.repository.ts
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/Grass.tsx
Labels: BE 💻, FE 🎨, Bug 🐞

#270 [FE] 엑세스 토큰 재발급 받기, 키워드 입력 안내문구 추가
  frontend/src/api/Detail.ts
  frontend/src/api/DiaryList.ts
  frontend/src/api/Edit.ts
  frontend/src/api/EmotionStat.ts
  frontend/src/api/Feed.ts
  frontend/src/api/FriendModal.ts
  frontend/src/api/Grass.ts
  frontend/src/api/KeywordSearch.ts
  frontend/src/api/Login.ts
  frontend/src/api/Profile.ts
  frontend/src/api/Reaction.ts
  frontend/src/api/fetchInterceptor.ts
  frontend/src/components/Edit/KeywordBox.tsx
Labels: FE 🎨, Feature 🎉

#276 [FE] 감정통계 UI 구성
  frontend/package.json
  frontend/src/components/Home/EmotionCloud.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/util/constants.ts
  yarn.lock
Labels: FE 🎨, Feature 🎉

#279 [FE] 오류 수정
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/EmotionStat.tsx
Labels: FE 🎨, Bug 🐞

#280 [FE] 오류 해결
  frontend/src/components/Home/EmotionStat.tsx
Labels: FE 🎨, Bug 🐞

#277 [FE] 의도와 다르게 동작하는 오류 수정
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
Labels: FE 🎨, Bug 🐞

#281 [공통] 오류 수정
  backend/src/diaries/diaries.repository.ts
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/EmotionCloud.tsx
  frontend/src/components/Home/EmotionStat.tsx
Labels: BE 💻, FE 🎨, Bug 🐞

#272 [BE] 태그로 일기 조회 시 반환값 에러 수정
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
Labels: BE 💻, Refactor 🛠️, Bug 🐞

#283 [BE] 친구 없는 사용자가 피드 조회 시 발생하는 에러 해결
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.service.ts
Labels: BE 💻, Bug 🐞

#289 [FE] 무한스크롤 IntersectionObserver 적용
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
Labels: FE 🎨, Feature 🎉

#292 [FE] 내가 작성한 일기 (주) 애니메이션 적용 & 버그 수정
  frontend/package.json
  frontend/src/api/EmotionStat.ts
  frontend/src/api/fetchInterceptor.ts
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/globals.css
  yarn.lock
Labels: FE 🎨, Bug 🐞, Feature 🎉

#294 [FE] 잔디, 수정 동작 수정
  .gitignore
  frontend/src/components/Home/Grass.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
Labels: enhancement, FE 🎨, Bug 🐞

#295 [FE] UX 개선, 의도치 않은 동작 수정
  frontend/src/assets/image/cryingCat.png
  frontend/src/assets/image/cryingFace.png
  frontend/src/assets/image/dashingAway.png
  frontend/src/assets/image/disappointedFace.png
  frontend/src/assets/image/dizzyFace.png
  frontend/src/assets/image/faceWithPeekingEye.png
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/FriendRequest.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
  frontend/src/components/Home/UserSearchContent.tsx
  frontend/src/pages/Detail.tsx
Labels: enhancement, FE 🎨, Bug 🐞

#306 [FE] 디자인 피드백 반영 & 키워드 1글자일 경우 검색 API 요청 보내지 않도록 처리
  frontend/src/assets/image/icons.svg
  frontend/src/assets/image/logo.svg
  frontend/src/assets/image/text_logo.png
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/globals.css
  frontend/src/pages/Detail.tsx
  frontend/src/util/constants.ts
  frontend/tailwind.config.js
Labels: enhancement, FE 🎨

#304 [FE] 글 작성자의 반응이 출력되는 문제 수정, UX 개선
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
Labels: enhancement, FE 🎨, Bug 🐞

#309 [FE] 단디 로고 배경색 변경
  frontend/index.html
  frontend/src/assets/image/logo.svg
  frontend/src/components/Home/EmotionStat.tsx
Labels: FE 🎨, Bug 🐞

#310 [FE] 돋보기 아이콘 위치수정
  frontend/src/components/Home/FriendRequest.tsx
Labels: FE 🎨

#314 [FE] 일기데이터 변경이 반영되지 않는 오류 수정, 피드백 반영
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendRequest.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/UserSearchContent.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
Labels: enhancement, FE 🎨, Bug 🐞

#315 [FE] 반응형 웹 디자인 적용 - 홈, 피드, 상세보기, 작성하기
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Keyword.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
Labels: FE 🎨

#316 [FE] 오류 수정 및 개선
  frontend/src/Router.tsx
  frontend/src/assets/image/chick.png
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Home/EmotionCloud.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/types/pages/MyDiary.ts
Labels: enhancement, FE 🎨, Bug 🐞

#311 [BE] 엘라스틱서치와 MySQL 데이터 동기화 방식 변경
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/reactions/reactions.repository.ts
  backend/src/reactions/reactions.service.ts
Labels: enhancement, BE 💻

#318 [BE] docker compose를 이용한 배포 구축
  .github/workflows/develop-cd.yml
  .github/workflows/docker-cd.yml
  Dockerfile.front
  Dockerfile.was
  dandi.conf
  docker-compose.yml
  frontend/src/util/apiPath.ts
Labels: BE 💻

#323 [BE] https 적용
  .github/workflows/docker-cd.yml
  Dockerfile.front
  Dockerfile.was
  dandi.conf
  docker-compose.yml
  frontend/src/util/apiPath.ts
Labels: BE 💻, Deploy 🚀

#320 [FE] 반응형 UI 수정
  frontend/src/api/fetchInterceptor.ts
  frontend/src/components/Common/Loading.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/util/constants.ts
Labels: FE 🎨, Bug 🐞

#324 [FE] Toast 구현
  frontend/src/App.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/hooks/useToast.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/util/ToastProvider.tsx
Labels: FE 🎨, Feature 🎉

#328 [FE] 잘못된 서버 URL 수정
  frontend/src/util/apiPath.ts
Labels: FE 🎨, Bug 🐞

#326 [BE] 검색 시 일기 ID를 조회할 수 없는 문제 수정
  backend/src/diaries/diaries.repository.ts
Labels: BE 💻, Bug 🐞

#329 [BE] 인프라 구조 변경
  .github/workflows/docker-cd.yml
  Dockerfile.front
  Dockerfile.nginx
  Dockerfile.was
  deploy.sh
  docker-compose.green.yml
  docker/docker-compose.base.yml
  docker/docker-compose.blue.yml
  nginx/dandi-blue.conf
  nginx/nginx.conf
Labels: BE 💻, Deploy 🚀

#331 [BE] github action 스크립트 수정
  .github/workflows/docker-cd.yml
Labels: BE 💻, Bug 🐞

#333 [BE] Dockerfile.nginx 경로 수정
  .github/workflows/docker-cd.yml
Labels: BE 💻, Deploy 🚀

#335 [BE] github action script에서 green 버전 제거
  .github/workflows/docker-cd.yml
Labels: BE 💻, Bug 🐞

#334 [FE] Home API 요청 최적화
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/types/components/Common/DiaryList.ts
Labels: enhancement, FE 🎨, Refactor 🛠️

#336 [FE] 오류 수정 & 모달 개선
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/EmotionCloud.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/hooks/useModal.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/util/ModalProvider.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: enhancement, FE 🎨, Bug 🐞

#339 [FE] LCP 최적화 1차
  frontend/index.html
  frontend/src/assets/image/text_logo.png
  frontend/src/assets/image/text_logo.webp
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Home/Profile.tsx
Labels: enhancement, FE 🎨

#340 [FE] 모달 개선사항 반영, 버그 수정
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/EmotionCloud.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/hooks/useModal.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/util/ModalProvider.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: FE 🎨, Bug 🐞

#343 [FE] Lighthouse 접근성, 권장사항 개선
  frontend/index.html
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
Labels: enhancement, FE 🎨

#344 [BE] 배포 관련 파일 정리
  Dockerfile.nginx
  deploy.sh
  docker-compose.green.yml
Labels: BE 💻, Deploy 🚀

#346 [FE] 뒤로가기 시 반응이 갱신 안되는 문제 수정
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/pages/Home.tsx
Labels: FE 🎨, Bug 🐞

#348 [FE] Modal div 여러 개 생기는 오류 해결
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/util/ModalProvider.tsx
Labels: FE 🎨, Bug 🐞

#352 [FE] 페이지 이동 시 모달이 닫히지 않는 문제 해결
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Home.tsx
Labels: FE 🎨, Bug 🐞

#350 [FE] 잔디 UI 수정
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/GrassTooltip.tsx
Labels: enhancement, FE 🎨

#354 [FE] 감정통계 UI 수정
  frontend/src/components/Home/EmotionStat.tsx
Labels: enhancement, FE 🎨

#359 [BE] 10MB 파일까지 입력 받을 수 있도록 변경
  nginx/dandi-blue.conf
  nginx/dandi-green.conf
  nginx/nginx.conf
Labels: enhancement, BE 💻

#360 [FE] 일기 작성, 삭제 시 업데이트 되지 않는 문제 수정
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
Labels: FE 🎨, Bug 🐞

#362 [FE] 날짜 관련 오류 & 상세페이지에 이모지가 제대로 반영되지 않는 문제 해결
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/util/funcs.ts
Labels: FE 🎨, Bug 🐞
