Repository boostcampwm2023/web18_Dandi, pull requests merged in 2023-11, with the labels that each got.

#5 [BE] 개발 환경 설정
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: BE

#6 [FE] 개발 환경 설정
  frontend/.eslintrc.cjs
  frontend/.prettierrc
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: FE

#9 [BE] CI 스크립트 작성
  .github/workflows/backend-ci.yml
Labels: BE

#13 [Common] 모노레포 적용
  .eslintrc.js
  .gitignore
  .prettierrc
  backend/.eslintrc.js
  backend/.prettierrc
  backend/package.json
  frontend/.eslintrc.cjs
  frontend/package.json
  package.json
  yarn.lock
Labels: BE 💻, FE 🎨

#10 [BE] 네이버 소셜 로그인 기능 구현
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.repository.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/createUserDto.ts
  backend/src/auth/dto/createUserResponseDto.ts
  backend/src/auth/entity/socialType.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/auth/guards/naverAuth.guard.ts
  backend/src/auth/strategy/naverAuth.strategy.ts
  backend/src/auth/utils/user.decorator.ts
  backend/src/configs/typeorm.config.ts
Labels: BE 💻, Feature

#14 [BE] 개발용 cd script 작성
  .github/workflows/develop-cd.yml
Labels: BE 💻

#17 [FE] tailwindcss 기본 설정
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/globals.css
  frontend/src/main.tsx
  frontend/tailwind.config.js
  yarn.lock
Labels: FE 🎨

#21 [BE] PM2를 이용한 무중단 배포 적용
  .github/workflows/develop-cd.yml
Labels: BE 💻

#25 [Common] .eslintrc.js 파일 수정
  backend/.eslintrc.js
  frontend/.eslintrc.js
Labels: Bug 🐞

#23 [BE] ci 스크립트 수정
  .github/workflows/backend-ci.yml
Labels: BE 💻, Bug 🐞

#20 [BE] JWT 로그인 기능 구현
  .gitignore
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.repository.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/createUserResponseDto.ts
  backend/src/auth/dto/user.dto.ts
  backend/src/auth/guards/jwtAuth.guard.ts
  backend/src/auth/guards/naverAuth.guard.ts
  backend/src/auth/strategy/jwtAuth.strategy.ts
  backend/src/auth/strategy/naverAuth.strategy.ts
  backend/src/auth/utils/jwt.type.ts
  backend/src/auth/utils/verifyCallback.ts
  backend/src/main.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#22 chore: 불필요한 코드 삭제 #7
  .github/workflows/develop-cd.yml
Labels: BE 💻

#29 [BE] swagger 적용
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/dto/user.dto.ts
  backend/src/configs/swagger.config.ts
  backend/src/main.ts
  yarn.lock
Labels: BE 💻, Docs 📄

#30 [Docs] gitignore에 .env 추가
  .format.env
  .gitignore
Labels: Docs 📄

#31 [FE] Common components UI 구성
  frontend/src/App.tsx
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/ProfileItem.tsx
Labels: FE 🎨

#32 [FE] Common 컴포넌트 구현
  frontend/src/assets/image/reactionEmoji.svg
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Reaction.tsx
Labels: FE 🎨

#35 [FE] tailwindCSS 플러그인 추가
  .prettierrc
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/ProfileItem.tsx
  frontend/src/components/Common/Reaction.tsx
  package.json
  yarn.lock
Labels: FE 🎨

#33 [BE] Logger 적용
  .gitignore
  backend/package.json
  backend/src/app.module.ts
  backend/src/configs/logger.config.ts
  backend/src/filter/logger.filter.ts
  backend/src/main.ts
  backend/src/middleware/logger.middleware.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#41 [FE] 로그인 페이지 UI 구성
  frontend/src/assets/image/logo.svg
  frontend/src/assets/image/naverLogin.svg
  frontend/src/components/Common/ProfileItem.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/pages/Login.tsx
Labels: FE 🎨

#42 [FE] NavBar 컴포넌트 구현
  frontend/index.html
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/globals.css
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  yarn.lock
Labels: FE 🎨, Feature 🎉

#44 [FE] 홈 프로필 섹션 UI 구현
  frontend/index.html
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/pages/Home.tsx
Labels: FE 🎨, Feature 🎉

#46 [FE] path alias 설정
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Common/ProfileItem.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/main.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: FE 🎨

#48 [FE] 로그인 API 연동 & path alias 수정
  frontend/src/api/Login.ts
  frontend/src/components/Login/LoginForm.tsx
  frontend/vite.config.ts
Labels: FE 🎨, Feature 🎉

#49 [FE] 로그인 API 연동
  frontend/src/api/Login.ts
  frontend/tsconfig.json
Labels: FE 🎨

#43 [BE] 일기 엔티티 생성
  backend/src/app.module.ts
  backend/src/diary/diary.module.ts
  backend/src/diary/entity/diary.entity.ts
  backend/src/diary/entity/diaryStatus.ts
  backend/src/diary/entity/tag.entity.ts
Labels: BE 💻, Feature 🎉

#37 [BE] refresh token 관리
  .format.env
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/guards/jwtAuth.guard.ts
  backend/src/auth/strategy/jwtAuth.strategy.ts
  backend/src/auth/utils/auth.constant.ts
  backend/src/auth/utils/customException.ts
  backend/src/configs/redis.config.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#51 [BE] auth module과 users module 분리
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.repository.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/auth/guards/naverAuth.guard.ts
  backend/src/auth/strategy/jwtAuth.strategy.ts
  backend/src/auth/strategy/naverAuth.strategy.ts
  backend/src/diary/entity/diary.entity.ts
  backend/src/users/entity/socialType.ts
  backend/src/users/entity/user.entity.ts
  backend/src/users/user.repository.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  backend/src/users/utils/user.decorator.ts
Labels: BE 💻, Refactor 🛠️

#53 [BE] 로그인 성공 시 redirect 되도록 변경
  backend/src/auth/auth.controller.ts
  backend/src/main.ts
Labels: enhancement, BE 💻

#65 [BE] file name 복수형으로 통일
  backend/src/auth/auth.service.ts
  backend/src/auth/strategy/jwtAuth.strategy.ts
  backend/src/users/users.module.ts
  backend/src/users/users.repository.ts
  backend/src/users/users.service.ts
Labels: BE 💻

#73 [FE] 일기 작성 페이지 구현
  frontend/package.json
  frontend/src/assets/image/lock.svg
  frontend/src/assets/image/unlocked.svg
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Edit/KeywordItem.tsx
  frontend/src/main.tsx
  frontend/src/pages/Edit.tsx
  yarn.lock
Labels: FE 🎨

#74 [BE] 닉네임으로 사용자검색 기능
  backend/src/users/dto/user.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.repository.ts
  backend/src/users/users.service.ts
Labels: BE 💻, Feature 🎉

#76 [BE] 일기 조회 API 구현
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/entity/diary.entity.ts
Labels: BE 💻, Feature 🎉

#79 [BE] typeORM 설정 분리
  .format.env
  backend/src/app.module.ts
  backend/src/configs/typeorm.config.ts
Labels: BE 💻

#80 [BE] 일기 수정 API 구현
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/utils/diaryStatus.validator.ts
Labels: BE 💻, Feature 🎉

#75 [FE] 내가 작성한 일기 - 헤더 & 일 UI 구성
  frontend/src/App.tsx
  frontend/src/assets/image/search.svg
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/tailwind.config.js
Labels: FE 🎨, Refactor 🛠️, Feature 🎉

#78 [FE] 일기 상세 페이지 UI 구성
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/pages/Detail.tsx
  frontend/tailwind.config.js
Labels: FE 🎨

#82 [BE] Friend Entity 생성 & 친구신청 기능 구현
  backend/src/app.module.ts
  backend/src/friends/dto/friend.dto.ts
  backend/src/friends/entity/friend.entity.ts
  backend/src/friends/entity/friendStatus.ts
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.module.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
  backend/src/users/entity/user.entity.ts
Labels: BE 💻, Feature 🎉

#88 [BE] 친구신청 취소
  backend/src/friends/dto/friend.dto.ts
  backend/src/friends/entity/friend.entity.ts
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
  backend/src/users/entity/user.entity.ts
Labels: BE 💻, Feature 🎉

#90 [Docs] README.md 수정
  README.md
Labels: Docs 📄

#84 [BE] 일기 삭제 API 구현
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
Labels: BE 💻, Feature 🎉

#95 [FE] CSS 속성, 일부 svg 아이콘 모듈화 적용
  frontend/src/assets/image/icons.svg
  frontend/src/assets/image/reactionEmoji.svg
  frontend/src/assets/image/search.svg
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/Icon.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/globals.css
  frontend/src/pages/Detail.tsx
  frontend/src/pages/MyDiary.tsx
Labels: FE 🎨, Refactor 🛠️

#98 [FE] 피드 페이지 구현
  frontend/src/Router.tsx
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/ProfileItem.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
Labels: FE 🎨

#94 [BE] Clova Summary 연동
  .format.env
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/entity/diary.entity.ts
  backend/src/users/entity/user.entity.ts
Labels: BE 💻, Feature 🎉

#106 [BE] 일기 반응 API / 리액션 목록 API 구현
  backend/src/app.module.ts
  backend/src/diaries/diaries.module.ts
  backend/src/diaries/diaries.service.ts
  backend/src/reactions/dto/reaction.dto.ts
  backend/src/reactions/entity/reaction.entity.ts
  backend/src/reactions/reactions.controller.ts
  backend/src/reactions/reactions.module.ts
  backend/src/reactions/reactions.repository.ts
  backend/src/reactions/reactions.service.ts
Labels: BE 💻, Feature 🎉

#93 [BE] 친구신청 수락 기능
  backend/src/friends/entity/friend.entity.ts
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
  backend/src/users/entity/user.entity.ts
Labels: BE 💻, Feature 🎉

#102 [FE] 내가 작성한 일기 - 월 UI 구성
  frontend/src/App.tsx
  frontend/src/assets/image/icons.svg
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/DateController.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/types/components/Common/DiaryList.ts
  frontend/src/types/pages/MyDiary.ts
  frontend/src/util/Calendar.ts
  frontend/src/util/MyDiary.ts
  frontend/src/util/dummyData.ts
  frontend/tailwind.config.js
Labels: FE 🎨, Feature 🎉

#109 [FE] 홈 - 친구관리 Modal
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/FriendRequest.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
Labels: FE 🎨

#96 [BE] 받은 친구신청 거절 기능 구현
  backend/src/friends/friends.controller.ts
Labels: BE 💻, Feature 🎉

#104 [BE] 친구 목록 조회 기능 구현
  backend/src/friends/dto/friend.dto.ts
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
  backend/src/friends/utils/friendsType.ts
Labels: BE 💻, Feature 🎉

#112 [BE] 리액션 삭제 API 구현
  backend/src/reactions/dto/reaction.dto.ts
  backend/src/reactions/reactions.controller.ts
  backend/src/reactions/reactions.service.ts
Labels: BE 💻, Feature 🎉

#113 [BE] 나의 친구목록에서 친구 검색 기능 구현
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
Labels: BE 💻, Feature 🎉

#116 [FE] path alias 자동 설정 오류 해결
  frontend/.eslintrc.js
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: FE 🎨, Bug 🐞

#121 [BE] Naver 로그인 방식 변경
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/auth/guards/naverAuth.guard.ts
  backend/src/auth/strategy/naverAuth.strategy.ts
  backend/src/users/users.repository.ts
Labels: enhancement, BE 💻

#123 [BE] 로그인 http method 수정
  backend/src/auth/auth.controller.ts
Labels: BE 💻, Bug 🐞

#126 [BE] 감정분석 AI 적용
  .format.env
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/utils/diaries.constant.ts
Labels: BE 💻, Feature 🎉

#125 [BE] 기간 내 일기 emotion 조회 API 작성
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
Labels: BE 💻, Feature 🎉

#119 [FE] 잔디 렌더링 관련 함수 롤백
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Edit/KeywordItem.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/GrassTooltip.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/util/Grass.ts
  frontend/tailwind.config.js
Labels: FE 🎨, Bug 🐞

#127 [FE] 내가 작성한 일기 - 주 UI 구성
  frontend/package.json
  frontend/src/assets/image/icons.svg
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Icon.tsx
  frontend/src/components/Common/Keyword.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/DateController.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/util/Calendar.ts
  frontend/src/util/MyDiary.ts
  frontend/src/util/constants.ts
  frontend/src/util/dummyData.ts
  frontend/src/util/funcs.ts
  yarn.lock
Labels: FE 🎨, Feature 🎉

#132 [BE] emotion 조회 API 요구사항 변경
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
Labels: enhancement, BE 💻

#135 [FE] ProfileEdit 빌드에러 수정
  frontend/src/components/Home/ProfileEdit.tsx
Labels: FE 🎨, Bug 🐞

#138 [FE] 네이버 로그인 API 연동
  frontend/.format.env
  frontend/src/Router.tsx
  frontend/src/api/Login.ts
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/pages/OAuthLogin.tsx
Labels: FE 🎨, Feature 🎉

#133 [BE] 최근 1년의 일기 mood 조회 기능
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/entity/diary.entity.ts
Labels: BE 💻, Feature 🎉

#137 [BE] 특정 사용자의 일기 조회 API 작성
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.module.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/dto/timeUnit.enum.ts
  backend/src/diaries/utils/diaries.constant.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: BE 💻, Feature 🎉

#143 [FE] 잔디 동작 방식 수정
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/GrassTooltip.tsx
Labels: enhancement, FE 🎨

#140 [BE] 사용자 조회 API 작성
  .gitignore
  backend/.gitignore
  backend/package.json
  backend/src/users/dto/user.dto.ts
  backend/src/users/entity/user.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.repository.ts
  backend/src/users/users.service.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#130 Clova Summary 오류 수정
  backend/src/diaries/diaries.service.ts
Labels: BE 💻, Bug 🐞

#141 [BE] 피드의 친구 일기 조회
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.module.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/entity/diary.entity.ts
  backend/src/diaries/utils/diaries.constant.ts
  backend/src/friends/friends.module.ts
Labels: BE 💻, Feature 🎉

#145 [FE] 디자인 일부 수정
  frontend/src/components/Common/Alert.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/globals.css
  frontend/tailwind.config.js
Labels: enhancement, FE 🎨

#160 [FE] 상수 분리 & DiaryListItem 컴포넌트 수정
  frontend/src/Router.tsx
  frontend/src/api/Login.ts
  frontend/src/assets/image/icons.svg
  frontend/src/components/Common/DiaryList.tsx
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Icon.tsx
  frontend/src/components/Common/Keyword.tsx
  frontend/src/components/Common/Modal.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Edit/KeywordItem.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/util/constants.ts
  frontend/src/util/funcs.ts
Labels: enhancement, FE 🎨, Refactor 🛠️

#162 [공통] CORS error 해결
  backend/src/main.ts
  frontend/src/api/Login.ts
  frontend/src/components/Login/LoginForm.tsx
Labels: BE 💻, FE 🎨, Bug 🐞

#169 [FE] API 주소 반환하는 객체추가, 참조오류 수정
  frontend/src/api/Login.ts
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/pages/OAuthLogin.tsx
  frontend/src/util/apiPath.ts
  frontend/src/util/constants.ts
Labels: FE 🎨, Bug 🐞

#171 프론트엔드 CI 설정 추가
  .github/workflows/ci.yml
Labels: FE 🎨

#173 [BE] cors error 해결
  backend/src/main.ts
Labels: Bug 🐞

#175 [BE] 일기 제목 & 본문 검색 API 작성
  backend/package.json
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/dto/diary.dto.ts
  backend/src/diaries/utils/diaries.constant.ts
  backend/src/diaries/utils/diaryStatus.validator.ts
  backend/src/reactions/reactions.service.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#174 [FE] 잔디 API 연동
  frontend/src/App.tsx
  frontend/src/api/Grass.ts
  frontend/src/components/Home/Grass.tsx
  frontend/src/util/apiPath.ts
Labels: FE 🎨, Feature 🎉

#178 [FE] 내가 작성한 일기 - 검색 옵션 및 검색 키워드 자동 완성 추가, Emoji Picker 위치 수정
  frontend/src/assets/image/icons.svg
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/Icon.tsx
  frontend/src/components/Common/Reaction.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/CarouselContainer.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/util/apiPath.ts
  frontend/tailwind.config.js
Labels: enhancement, FE 🎨

#179 [FE] 일기 작성 API 연동, 입력한 키워드 삭제 구현
  frontend/src/api/Edit.ts
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/pages/Edit.tsx
Labels: FE 🎨, Feature 🎉

#182 [FE] 일기 작성 페이지 - 유효성 검사가 작동하지 않는 문제 수정
  frontend/src/pages/Edit.tsx
Labels: FE 🎨, Bug 🐞

#180 [BE] 일기 조회 API 응답 수정
  backend/src/diaries/diaries.controller.ts
  backend/src/diaries/dto/diary.dto.ts
Labels: BE 💻, Bug 🐞

#183 [FE] 유저 정보 조회 API 연동
  frontend/src/api/Profile.ts
  frontend/src/components/Home/Profile.tsx
  frontend/src/pages/Home.tsx
  frontend/src/util/apiPath.ts
Labels: FE 🎨, Feature 🎉

#186 [BE] object storage에 이미지 업로드 기능 구현
  .format.env
  backend/package.json
  backend/src/app.module.ts
  backend/src/configs/objectStorage.config.ts
  backend/src/images/images.controller.ts
  backend/src/images/images.module.ts
  backend/src/images/images.repository.ts
  backend/src/images/images.service.ts
  backend/src/images/utils/images.constant.ts
  yarn.lock
Labels: BE 💻, Feature 🎉

#189 [BE] 친구 목록 조회 API 분리
  backend/src/friends/friends.controller.ts
  backend/src/friends/friends.service.ts
Labels: BE 💻, Refactor 🛠️

#190 [FE] 홈 페이지 - 친구목록 탭 API 연동
  frontend/src/api/FriendModal.ts
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/Profile.tsx
Labels: FE 🎨, Feature 🎉

#191 [FE] 일기 삭제 API 연동
  frontend/src/api/Detail.ts
  frontend/src/api/ReferDiary.ts
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
Labels: FE 🎨, Feature 🎉

#194 [FE] 반응 조회 API 연동
  frontend/src/api/Reaction.ts
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/util/apiPath.ts
Labels: FE 🎨, Feature 🎉

#196 [FE] 친구관리 탭 API 연동 - 진행중인 친구 요청목록, 사용자 검색, 친구요청 보내기
  frontend/src/api/FriendModal.ts
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/FriendRequest.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
  frontend/src/components/Home/UserSearchContent.tsx
  frontend/src/util/apiPath.ts
  frontend/src/util/constants.ts
Labels: FE 🎨, Feature 🎉

#198 [FE] 일기 내용에 html 태그가 보이는 문제 수정
  frontend/package.json
  frontend/src/components/Detail/DiaryContent.tsx
  yarn.lock
Labels: enhancement, FE 🎨

#195 [BE] 키워드 검색 시 추천 태그 조회 API 구현
  backend/src/diaries/diaries.service.ts
  backend/src/tags/dto/tag.dto.ts
  backend/src/tags/tag.repository.ts
  backend/src/tags/tags.controller.ts
  backend/src/tags/tags.module.ts
  backend/src/tags/tags.service.ts
Labels: BE 💻, Feature 🎉
