Repository boostcampwm2023/web18_Dandi, pull requests merged in 2024-02, with the labels that each got.

#386 [BE] Images e2e 테스트 작성
  backend/package.json
  backend/test/images/images.e2e-spec.ts
  backend/test/images/testFile.txt
  frontend/package.json
  yarn.lock
Labels: BE 💻

#385 [FE] userId를 localStorage에서 store객체로 분리
  frontend/src/api/DiaryList.ts
  frontend/src/api/fetchInterceptor.ts
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/Home/UserSearchContent.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/hooks/useCreateDiaryMutation.ts
  frontend/src/hooks/useDayDiaryListQuery.ts
  frontend/src/hooks/useDeleteDiaryMutation.ts
  frontend/src/hooks/useEmotionStatQuery.ts
  frontend/src/hooks/useFeedDiaryListQuery.ts
  frontend/src/hooks/useGrassQuery.ts
  frontend/src/hooks/useMonthDiaryDataQuery.ts
  frontend/src/hooks/useMyDayDiaryListQuery.ts
  frontend/src/hooks/useMyWeekDiaryQuery.ts
  frontend/src/hooks/useProfileDataQuery.ts
  frontend/src/hooks/useUpdateDiaryMutation.ts
  frontend/src/hooks/useUpdateProfileMutation.ts
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/pages/OAuthLogin.tsx
  frontend/src/store/useUserStore.ts
  frontend/src/util/AuthRoutes.tsx
  frontend/src/util/PrivateRoutes.tsx
  frontend/src/util/apiPath.ts
Labels: enhancement, FE 🎨

#384 [BE] Tag e2e 테스트 작성
  backend/src/tags/tags.service.ts
  backend/test/tags/app.e2e-spec.ts
  backend/test/tags/tags.e2e-spec.ts
Labels: BE 💻

#387 [BE] Diary E2E 테스트 작성
  backend/src/configs/typeorm.config.ts
  backend/src/diaries/diaries.repository.ts
  backend/src/tags/tags.service.ts
  backend/test/diaries/dairies.e2e-spec.ts
  backend/test/tags/app.e2e-spec.ts
  backend/test/tags/tags.e2e-spec.ts
Labels: BE 💻

#388 [BE] Friends Module e2e 테스트 작성
  backend/src/configs/typeorm.config.ts
  backend/src/friends/friends.repository.ts
  backend/src/friends/friends.service.ts
  backend/test/friends/friends.e2e-spec.ts
  backend/test/utils/testLogin.ts
Labels: enhancement, BE 💻

#393 [FE] 로컬 스토리지 초기화 오류 해결
  frontend/src/api/fetchInterceptor.ts
  frontend/src/pages/OAuthLogin.tsx
Labels: FE 🎨, Bug 🐞

#390 [BE] Users Controller e2e 테스트 작성
  backend/src/configs/typeorm.config.ts
  backend/test/users/testFile.txt
  backend/test/users/users.e2e-spec.ts
Labels: enhancement, BE 💻

#389 [BE] Auth E2E 테스트 작성
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/test/auth/auth.e2e-spec.ts
  backend/test/utils/testLogin.ts
Labels: BE 💻

#391 [BE] Reactions e2e 테스트
  backend/test/reactions/reactions.e2e-spec.ts
Labels: enhancement, BE 💻
