Repository boostcampwm2023/web18_Dandi, pull requests merged in 2024-01, with the labels that each got.

#366 [FE] 상태관리 라이브러리 적용
  frontend/package.json
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/store/useViewTypeStore.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
  yarn.lock
Labels: enhancement, FE 🎨

#365 [BE] Friends 모듈 테스트 작성
  .gitignore
  backend/package.json
  backend/src/friends/entity/friend.entity.ts
  backend/src/friends/friends.service.spec.ts
  backend/src/friends/friends.service.ts
Labels: enhancement, BE 💻

#368 [BE] Tags 모듈 단위 테스트 작성
  backend/src/diaries/diaries.service.ts
  backend/src/tags/tags.module.ts
  backend/src/tags/tags.repository.ts
  backend/src/tags/tags.service.spec.ts
  backend/src/tags/tags.service.ts
Labels: enhancement, BE 💻

#369 [FE] Edit 페이지 상태 분리
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/store/useEditStore.ts
  frontend/src/store/useViewTypeStore.ts
Labels: enhancement, FE 🎨

#370 [BE] users service 유닛 테스트 작성
  backend/src/users/users.service.spec.ts
Labels: enhancement, BE 💻

#371 [FE] Edit 페이지 state 전달 방식 수정
  frontend/src/components/Edit/Editor.tsx
  frontend/src/components/Edit/Header.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Edit.tsx
  frontend/src/store/useEditStore.ts
Labels: enhancement, FE 🎨

#372 [BE] diaries service에서 AI로직 utils로 분리
  backend/src/diaries/diaries.service.ts
  backend/src/diaries/utils/clovaRequest.ts
Labels: BE 💻, Refactor 🛠️

#375 [FE] vite 버전 업데이트
  frontend/package.json
  yarn.lock
Labels: enhancement, FE 🎨

#376 [FE] 컴포넌트에서 직접 호출하는 useQuery를 커스텀 훅으로 분리
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Common/NavBar.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Diary/ReactionList.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/EmotionStat.tsx
  frontend/src/components/Home/FriendList.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/FriendSearchContent.tsx
  frontend/src/components/Home/Grass.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ReceivedRequest.tsx
  frontend/src/components/Home/SendRequest.tsx
  frontend/src/components/Home/UserSearchContent.tsx
  frontend/src/components/Login/LoginForm.tsx
  frontend/src/components/MyDiary/Calendar.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/components/MyDiary/DayItem.tsx
  frontend/src/components/MyDiary/MonthContainer.tsx
  frontend/src/components/MyDiary/ViewType.tsx
  frontend/src/components/MyDiary/WeekContainer.tsx
  frontend/src/hooks/useDayDiaryListQuery.ts
  frontend/src/hooks/useDiaryQuery.ts
  frontend/src/hooks/useEmotionStatQuery.ts
  frontend/src/hooks/useFeedDiaryListQuery.ts
  frontend/src/hooks/useFriendListQuery.ts
  frontend/src/hooks/useGrassQuery.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useMonthDiaryDataQuery.ts
  frontend/src/hooks/useMyDayDiaryListQuery.ts
  frontend/src/hooks/useMyWeekDiaryQuery.ts
  frontend/src/hooks/useProfileDataQuery.ts
  frontend/src/hooks/useReactionListQuery.ts
  frontend/src/hooks/useRequestListQuery.ts
  frontend/src/hooks/useSearchDataListQuery.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Feed.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/MyDiary.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/util/constants.ts
Labels: enhancement, FE 🎨

#378 [BE] diary service 유닛테스트
  backend/src/diaries/diaries.service.spec.ts
Labels: enhancement, BE 💻

#379 [BE] auth/images 단위 테스트 작성
  backend/src/auth/auth.repository.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/images/images.controller.ts
  backend/src/images/images.service.spec.ts
  backend/test/testImage.png
Labels: BE 💻

#377 [FE] 컴포넌트에서 직접 호출하는 useMutation을 커스텀 훅으로 분리
  frontend/src/components/Common/DiaryListItem.tsx
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/Edit/KeywordBox.tsx
  frontend/src/components/Home/FriendModalItem.tsx
  frontend/src/components/Home/Profile.tsx
  frontend/src/components/Home/ProfileEdit.tsx
  frontend/src/components/MyDiary/Card.tsx
  frontend/src/hooks/useAllowFriendMutation.ts
  frontend/src/hooks/useCancelRequestMutation.ts
  frontend/src/hooks/useCreateDiaryMutation.ts
  frontend/src/hooks/useDeleteDiaryMutation.ts
  frontend/src/hooks/useDeleteFriendMutation.ts
  frontend/src/hooks/useDeleteReactionMutation.ts
  frontend/src/hooks/usePostReactionMutation.ts
  frontend/src/hooks/useReactionListQuery.ts
  frontend/src/hooks/useRejectFriendMutation.ts
  frontend/src/hooks/useRequestFriendMutation.ts
  frontend/src/hooks/useUpdateDiaryMutation.ts
  frontend/src/hooks/useUpdateProfileMutation.ts
  frontend/src/pages/Detail.tsx
Labels: enhancement, FE 🎨

#381 [FE] 오류 수정
  frontend/src/components/Detail/DiaryContent.tsx
  frontend/src/components/MyDiary/KeywordSearch.tsx
  frontend/src/globals.css
  frontend/src/pages/Feed.tsx
  frontend/src/types/pages/MyDiary.ts
Labels: FE 🎨, Bug 🐞
